quiz = {
    1: {
        "question": "Gran parte de las moleculas biológicas son macromoleculas, polimeros de alta masa molecular que se constituyen a partir de...",
        "options": ["monomeros", "proteinas", "aminoacidos"],
        "clues": ["Moléculas de pequeña masa molecular"],
        "explanation": "Los polímeros son macromoléculas compuestas por una o varias unidades químicas (conocidas como monómeros) que se repiten a lo largo de toda la cadena. Imagínate, por ejemplo, un collar de perlas: cada una de las perlas sería un monómero mientras que el collar entero es lo que se conoce como polímero.",
        "reference": "https://www.zschimmer-schwarz.es/noticias/que-son-los-polimeros-y-como-se-clasifican",
        "answer": "monomeros",
    },
    2: {
        "question": "Existen 20 aminoacidos codificados en el...",
        "options": ["ARNm", "codigo genetico"],
        "clues": ["placeholder"],
        "explanation": "placeholder",
        "reference": "placeholder",
        "answer": "codigo genetico",
    },
    3: {
        "question": "Asi como todas las proteinas son consideradas polipeptidos, todos los polipeptidos a su vez son consideradas proteinas.",
        "options": ["verdadero", "falso"],
        "clues": ["placeholder"],
        "explanation": "placeholder",
        "reference": "placeholder",
        "answer": "falso",
    },
    4: {
        "question": "Dentro de los mecanismos de la expresion génica, a la produccion de copias de ARNm a partir de ADN se denomina...",
        "options": ["transcripcion", "traduccion", "remodelación de la cromatina"],
        "clues": ["placeholder"],
        "explanation": "placeholder",
        "reference": "placeholder",
        "answer": "transcripcion",
    },
    5: {
        "question": "A diferencias de las celular procariotas, las celular eucariotas se caracterizan por tener...",
        "options": ["nucleo", "mayor tamaño", "citoesqueleto", "todas las anteriores"],
        "clues": ["placeholder"],
        "explanation": "placeholder",
        "reference": "placeholder",
        "answer": "todas las anteriores",
    },
    6: {
        "question": "Las proteinas son macromoleculas, cuyas cadenas de unidades de aminoacidos se encuentran unidos por medio de enlaces peptidicos entre...",
        "options": [
            "un grupo carboxilos y un grupo amino",
            "si mismas formando un bucle",
            "grupos fosfatos",
            "ninguna de las anteriores",
        ],
        "clues": ["placeholder"],
        "explanation": "placeholder",
        "reference": "placeholder",
        "answer": "un grupo carboxilos y un grupo amino",
    },
    7: {
        "question": 'El termino "genoma" se refiere a...',
        "options": [
            "toda la informacion contenida en el ADN de una célula",
            "un segmento particular del ADN con una secuencia particular de nucleótidos",
            "todas las anteriores",
        ],
        "clues": ["placeholder"],
        "explanation": "placeholder",
        "reference": "placeholder",
        "answer": "toda la informacion contenida en el ADN de una célula",
    },
    8: {
        "question": "Los aminoacidos no escenciales son aquellos que no pueden ser sintetizados por el hombre, a la velocidad o cantidad suficiente para disponer de ellos, por lo que tienen que ser aportados por los alimentos de la dieta y esto condiciona su esencialidad.",
        "options": ["verdadero", "falso"],
        "clues": ["placeholder"],
        "explanation": "placeholder",
        "reference": "placeholder",
        "answer": "falso",
    },
}
