quiz = {
    1: {
        "question": "Gran parte de las moleculas biológicas son macromoleculas, polimeros de alta masa molecular que se constituyen a partir de...",
        "options": ["monomeros", "proteinas", "aminoacidos"],
        "clues": ["Moléculas de pequeña masa molecular"],
        "explanation": "Los polímeros son macromoléculas compuestas por una o varias unidades químicas (conocidas como monómeros) que se repiten a lo largo de toda la cadena. Imagínate, por ejemplo, un collar de perlas: cada una de las perlas sería un monómero mientras que el collar entero es lo que se conoce como polímero.",
        "reference": "https://www.zschimmer-schwarz.es/noticias/que-son-los-polimeros-y-como-se-clasifican",
        "answer": "monomeros",
    },
    2: {
        "question": "Los aminoácidos son un conjunto de 20 tipos distintos de moléculas y constituyen las piezas básicas para construir...",
        "options": ["vitamínas", "proteínas", "minerales"],
        "clues": ["Constan de una o más cadenas de aminoácidos", "estas cadenas se llaman polipéptidos"],
        "explanation": "Las proteínas son moléculas grandes y complejas que cumplen muchas funciones importantes en el cuerpo. Son vitales para la mayoría de los trabajos que realizan las células y son necesarias para mantener la estructura, función y regulación de los tejidos y órganos del cuerpo. Una proteína está formada por una o más cadenas largas, plegadas de aminoácidos (cada una llamada polipéptido), cuyas secuencias están determinadas por la secuencia de ADN del gen que codifica la proteína.",
        "reference": "https://www.genome.gov/es/genetics-glossary/Proteina",
        "answer": "proteínas",
    },
    3: {
        "question": "¿Que estructura intercelular formada por ARN y proteínas es la encargada de la sintesis proteica en las célular?",
        "options": ["centriolo", "ribosoma", "mitocondria", "nucleo"],
        "clues": ["Cumple la funcion de traduccion dentro de la expresión genica"],
        "explanation": "Los ribosomas son una parte de la fábrica de generación de proteínas en la célula. El propio ribosoma es una estructura de dos subunidades que se une al ARN mensajero. Esta estructura actúa como una estación de acoplamiento para la transferencia de ARN que contiene el aminoácido que pasará a formar parte de la cadena polipeptídica en crecimiento, que a la larga se convierte en una proteína.",
        "reference": "https://www.genome.gov/es/genetics-glossary/Ribosoma",
        "answer": "ribosoma",
    },
    4: {
        "question": "Dentro de los mecanismos de la expresion génica, el proceso de generar una copia de ARN a partir de ADN se conoce como...",
        "options": ["transcripcion", "traduccion", "remodelación de la cromatina"],
        "clues": ["A esta copia se la conoce como ARN mensajero (ARNm)"],
        "explanation": "La transcripción, en lo que se relaciona a la genómica, es el proceso de generación de una copia de ARN a partir de una secuencia de ADN de un gen. Esta copia, llamada ARN mensajero (ARNm), es portadora de la información sobre la proteína que el gen tiene codificada en ADN. En los seres humanos y otros organismos complejos, el ARN se desplaza desde el núcleo de la célula al citoplasma de la célula (compartimento acuoso), donde se usa para sintetizar la proteína codificada.",
        "reference": "https://www.genome.gov/es/genetics-glossary/Transcripcion",
        "answer": "transcripcion",
    },
    5: {
        "question": "A diferencias de las celulas procariotas, las celular eucariotas se caracterizan por tener...",
        "options": ["nucleo", "mayor tamaño", "citoesqueleto", "todas las anteriores"],
        "clues": ["La palabra \"eucariota\" es de origen griego, cuyo significado es \"núcleo verdadero\""],
        "explanation": "La célula eucariota tiene una membrana que encierra el núcleo separándolo del citoplasma. La célula procariota no posee estructuras con membranas en su interior, es decir, su contenido intracelular está esparcido en el citoplasma.",
        "reference": "https://www.diferenciador.com/celula-eucariota-y-celula-procariota/",
        "answer": "todas las anteriores",
    },
    6: {
        "question": "Las cadenas de unidades de aminoacidos que componen una proteina se encuentran unidos por medio de enlaces peptidicos entre...",
        "options": [
            "un grupo carboxilo y un grupo amino",
            "si mismas formando un bucle",
            "grupos fosfatos",
            "ninguna de las anteriores",
        ],
        "clues": ["La estructura de uno de los grupos se puede representar como -COOH", "Uno de los grupos es un grupo funcional derivado del amoníaco"],
        "explanation": "Los aminoácidos son moléculas orgánicas pequeñas que contienen un grupo carboxilo (COOH) y un grupo amino (NH2). El grupo carboxilo es ácido débil, mientras que el grupo amino es básico débil.",
        "reference": "https://www.uv.es/tunon/pdf_doc/trabajo_matilde.pdf",
        "answer": "un grupo carboxilo y un grupo amino",
    },
    7: {
        "question": 'El termino "genoma" se refiere a...',
        "options": [
            "toda la informacion contenida en el ADN de una célula",
            "un segmento particular del ADN con una secuencia particular de nucleótidos",
            "todas las anteriores",
        ],
        "clues": ["Conjunto completo de instrucciones de un organismo"],
        "explanation": "El genoma es el conjunto completo de instrucciones del ADN que se hallan en una célula. En los seres humanos, el genoma consta de 23 pares de cromosomas ubicados en el núcleo de la célula, así como de un pequeño cromosoma en la mitocondria de la célula. Un genoma contiene toda la información que una persona necesita para desarrollarse y funcionar.",
        "reference": "placeholder",
        "answer": "toda la informacion contenida en el ADN de una célula",
    }
}
